### ISSUE TITLE
Edit error..

### ISSUE THREAD

**Issue by bewuluck0912** [sagar9268/Memoir#34]
Logcat Message : java.lang.ClassCastException: com.bumptech.glide.load.resource.bitmap.GlideBitmapDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
        at com.sagar.memoir.ImageUtils.drawableToByteArray(ImageUtils.java:14)
        at com.sagar.memoir.DatabaseHelper.updateJournal(DatabaseHelper.java:138)
        at com.sagar.memoir.JournalEntryActivity.editJournal(JournalEntryActivity.java:253)
        at com.sagar.memoir.JournalEntryActivity.access$400(JournalEntryActivity.java:34)
        at com.sagar.memoir.JournalEntryActivity$2.onClick(JournalEntryActivity.java:127)

If have image...
when click save,,error occurs

**Comment by sagar9268** [comment]
Yes there seems to be a bug in that. Good job.
@bewuluck0912   can you resolve the issue?
